modify my tests to work with anvil

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -37,12 +37,23 @@ jobs:
           forge build --sizes
         id: build
 
-      - name: Create anvil instance
+      - name: Create and run anvil instance
         run: |
-          anvil --fork-url https://eth-mainnet.g.alchemy.com/v2/u8KNGev4YJSxig_yx_xMM2Gnn4CutPat
+          anvil --fork-url https://eth-mainnet.g.alchemy.com/v2/u8KNGev4YJSxig_yx_xMM2Gnn4CutPat &
+          echo $! > /tmp/anvil.pid  # Save the PID
+          while ! nc -z localhost 8545; do
+            sleep 1
+          done
         id: anvil
 
       - name: Run Forge tests
         run: |
           forge test -vvv --fork-url http://127.0.0.1:8545
         id: test
+
+      - name: Cleanup anvil
+        if: always()  # Run this step even if tests fail
+        run: |
+          if [ -f /tmp/anvil.pid ]; then
+            kill $(cat /tmp/anvil.pid)
+          fi
